src/surf_swap/config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/inbox', to: 'pages#inbox', as: 'inbox'

  #################### BOARDS ###############################

  get '/boards', to: 'boards#index', as: 'boards'
  post '/boards', to: 'boards#create'

  get '/boards/new', to: 'boards#new', as: 'new_board'

  get '/boards/:id', to: 'boards#show', as: 'board'
  delete '/boards/:id', to: 'boards#destroy'
  patch '/boards/:id', to: 'boards#update'
  
  get '/boards/:id/edit', to: 'boards#edit', as: 'edit_board'
  
  

#################### LISTINGS ###############################

  # TO LISTINGS
  get '/listings', to: 'listings#index', as: 'listings'
  post '/listings', to: 'listings#create'

  # NEW LISTING
  get '/listings/new', to: 'listings#new', as: 'new_listing'

  # SPECIFIC LISTING
  get '/listings/:id', to: 'listings#show', as: 'listing'
  patch '/listings/:id', to: 'listings#update'
  delete '/listings/:id', to: 'listings#destroy'

  # SPECIFIC LISTING + EDIT
  get '/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'

  ##################### USER LISTINGS ###########################

  get '/my-listings', to: 'listings#my_listings', as: 'my_listings'
  get '/user-listings/:id', to: 'listings#see_user_listings', as: 'see_user_listings'

  #################### offers ###############################

  get '/offers', to: 'offers#index', as: 'offers'
  post '/offers', to: 'offers#create'

  get '/listings/:id/offer/new', to: 'offers#new', as: 'new_offer'

  get '/offers/:id', to: 'offers#show', as: 'offer'
  patch '/offers/:id', to: 'offers#update'
 
  delete '/offers/:id', to: 'offers#destroy'

  get '/offers/:id/edit', to: 'offers#edit', as: 'edit_offer'


  #################### ACCEPT REJECT ###############################

  get '/reject-offer/:id', to: 'offers#reject_offer', as: 'reject_offer'
  get '/accept-offer/:id', to: 'meetups#create', as: 'accept_offer'
  get '/reset-offer/:id', to: 'offers#reset_offer', as: 'reset_offer'

  #################### MEETUPS ###############################

  get '/meetups', to: 'meetups#index', as: 'meetups'
  get '/meetups/new', to: 'meetups#new', as: "new_meetup"
  post '/meetups', to: 'meetups#create'
  
  get '/meetups/:id/edit', to: 'meetups#edit', as: 'edit_meetup'

  get '/meetups/:id', to: 'meetups#show', as: 'meetup'
  patch '/meetups/:id', to: 'meetups#update'
  delete '/meetups/:id', to: 'meetups#destroy'

  ##################### USER CANCELLATIONS ###########################

  get '/meetups/swap-completed/:id', to: 'meetups#swap_completed', as: 'swap_completed'
  get '/meetups/host-cancellation/:id', to: 'meetups#host_cancels', as: 'host_cancellation'
  get '/meetups/cancellation/:id', to: 'meetups#responder_cancels', as: 'responder_cancellation'
  
end

src/surf_swap/app/views/layouts/_nav.html.erb
<header class="p-3 bg-dark text-white">
<!-- <header class="p-3 bg-dark text-white .navbar-expand-md fixed-top"> -->

  <div class="container">

    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <a href="" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

   

      <%= render '/layouts/nav_lhs_links' %>
     
      <%= render '/layouts/nav_flash_output_AN' %>

     
      <%= render '/layouts/nav_rhs_buttons' %>

    </div>

  </div>

</header>

   

  

src/surf_swap/app/views/layouts/_nav_flash_output_AN.html.erb
<% if notice %>

  <span class="notice"
    style="color:grey"
    class="px-2 nav col-12 col-lg-auto me-sm-auto mb-2 justify-content-center mb-md-0"><%= notice %>
    &nbsp;&nbsp;&nbsp;&nbsp;
  </span>

<% elsif alert %>

  <span class="alert"
    style="color: orange"
    class="px-2 nav col-12 col-lg-auto me-sm-auto mb-2 justify-content-center mb-md-0"><%= alert %>
    &nbsp;&nbsp;&nbsp;&nbsp;
  </span>

<% end %>

src/surf_swap/app/views/layouts/_nav_flash_output_E.html.erb
<% if flash[:errors] %>  

<section id="errors">
  <% flash[:errors].each do |error| %>
    <span style="color:red"
    class="px-2 nav col-12 col-lg-auto me-sm-auto mb-2 justify-content-center mb-md-0">
      !&nbsp;&nbsp;<%= error %>&nbsp;&nbsp;!&nbsp;&nbsp;&nbsp;&nbsp;
    </span>
  <% end %>
</section>

<% end %>

src/surf_swap/app/views/layouts/_nav_lhs_links.html.erb
<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
  <li>&nbsp;&nbsp;&nbsp;&nbsp;</li>
  <li><%= link_to "Home", root_path, class: "nav-link px-8 text-white"%></li>
  <li><%= link_to "View All Listings", listings_path, class: "nav-link px-8 text-white" %></li>
  <li><a href="/#faqs" class="nav-link px-8 text-white">FAQs</a></li>
</ul>

src/surf_swap/app/views/layouts/_nav_rhs_buttons.html.erb
<% if user_signed_in? %>

  <div class="text-end">     
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-light me-2"  %>          
  </div>

  <div class="text-end">
    <p class="nav-link px-2 text-secondary nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" >
    &nbsp;&nbsp;Hi <%= current_user.first_name %>!
    </p>
  </div>


<% else %>

  <div class="text-end">
    <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light me-2"%>
  </div>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <div class="text-end">
    <%= link_to "Sign-up", new_user_registration_path, class: "btn btn-warning"%>
  </div>

<% end %>

src/surf_swap/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurfSwap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

   
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <%= render '/layouts/nav' %>
  
    <%= yield %>
    <%# DEVISE MESSAGES - notice for successes, alerts for failures %>
 
  </body>
</html>