src/surf_swap/config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/inbox', to: 'pages#inbox', as: 'inbox'

  #################### BOARDS ###############################

  get '/boards', to: 'boards#index', as: 'boards'
  post '/boards', to: 'boards#create'

  get '/boards/new', to: 'boards#new', as: 'new_board'

  get '/boards/:id', to: 'boards#show', as: 'board'
  delete '/boards/:id', to: 'boards#destroy'
  patch '/boards/:id', to: 'boards#update'
  
  get '/boards/:id/edit', to: 'boards#edit', as: 'edit_board'
  
  

#################### LISTINGS ###############################

  # TO LISTINGS
  get '/listings', to: 'listings#index', as: 'listings'
  post '/listings', to: 'listings#create'

  # NEW LISTING
  get '/listings/new', to: 'listings#new', as: 'new_listing'

  # SPECIFIC LISTING
  get '/listings/:id', to: 'listings#show', as: 'listing'
  patch '/listings/:id', to: 'listings#update'
  delete '/listings/:id', to: 'listings#destroy'

  # SPECIFIC LISTING + EDIT
  get '/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'

  ##################### USER LISTINGS ###########################

  get '/my-listings', to: 'listings#my_listings', as: 'my_listings'
  get '/user-listings/:id', to: 'listings#see_user_listings', as: 'see_user_listings'

  #################### offers ###############################

  get '/offers', to: 'offers#index', as: 'offers'
  post '/offers', to: 'offers#create'

  get '/listings/:id/offer/new', to: 'offers#new', as: 'new_offer'

  get '/offers/:id', to: 'offers#show', as: 'offer'
  patch '/offers/:id', to: 'offers#update'
 
  delete '/offers/:id', to: 'offers#destroy'

  get '/offers/:id/edit', to: 'offers#edit', as: 'edit_offer'


  #################### ACCEPT REJECT ###############################

  get '/reject-offer/:id', to: 'offers#reject_offer', as: 'reject_offer'
  get '/accept-offer/:id', to: 'meetups#create', as: 'accept_offer'
  get '/reset-offer/:id', to: 'offers#reset_offer', as: 'reset_offer'

  #################### MEETUPS ###############################

  get '/meetups', to: 'meetups#index', as: 'meetups'
  get '/meetups/new', to: 'meetups#new', as: "new_meetup"
  post '/meetups', to: 'meetups#create'
  
  get '/meetups/:id/edit', to: 'meetups#edit', as: 'edit_meetup'

  get '/meetups/:id', to: 'meetups#show', as: 'meetup'
  patch '/meetups/:id', to: 'meetups#update'
  delete '/meetups/:id', to: 'meetups#destroy'

  ##################### USER CANCELLATIONS ###########################

  get '/meetups/swap-completed/:id', to: 'meetups#swap_completed', as: 'swap_completed'
  get '/meetups/host-cancellation/:id', to: 'meetups#host_cancels', as: 'host_cancellation'
  get '/meetups/cancellation/:id', to: 'meetups#responder_cancels', as: 'responder_cancellation'
  
end

src/surf_swap/app/views/pages/_faqs.html.erb
<section id="faqs" 
class="d-flex h-100vh text-center text-white bg-dark d-flex justify-content-center">

  <div class="pt-4 pb-3" style="max-width:400px">
      <h4 class="mb-4"> FAQs </h4>
      <hr class="mt-3 mb-3">

      <p class="fw-bold left">Is it really free ?</p>
      <p> Yes! This platform is designed to allow people to swap their surf gear and do our part in 
        creating a sustainable environment.
      </p><br>

      <p class="fw-bold left">Is this legitimate ?</p> 
      <p>Also Yes! You can view Listings where other people are offering to swap their stuff, and make an 
        offer, or you can make a Listing yourself, you just need a free account to get started. 
      </p><br>

      <p class="fw-bold left">So how do you make your money ?</p> 
      <p>Most of the time, we don't ! If you want a premium account, which lists your gear at the top of the 
        Listings, and gives you more Listings to host at once. Our free accounts still let you have 2 Listings
        simultaneously, so if that's all you need, you are good to go! <span style="color:mediumseagreen">Also 
        at the moment all of our account holders can have unlimited use for a short time only.</span>
      </p><br>

      <p class="fw-bold left">So what's next ?</p> 
      <p>If you haven't signed up, then do this first. We only need your email and first name, and you can give
        your phone number there as well. Phone numbers are not given to anyone until you agree to a swap, and we don't share your number otherwise.
        <br><br>
        Once you have signed up, add a surfboard or surfboards to your profile ("Add a Board"). You can use this to 
        offer swaps, or make a Listing of your own, and see what other people want to offer you as a trade!
        <br><br>
        So checkout Listings and offer your own gear to swap with someone, or make your own Listing. It's up to you! 
        If the host of a listing agrees to a swap offer, then a meetup will automatically be created. Make sure you get 
        there on time, and you can make the trade. It's as easy as that.</p><br>

      <hr class="mt-2 mb-5">   
  </div>

</section>

src/surf_swap/app/views/pages/_header.html.erb
<header>
  <div class="bg-dark collapse" id="navbarHeader" style="">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

</header>

src/surf_swap/app/views/pages/_learn_more.html.erb
<section 
id="learn_more"
class="d-flex h-100vh text-center text-white bg-dark d-flex justify-content-center" >

  <div class="pt-4 pb-3" style="max-width:400px"> 
      <h4 class="mb-4"> Learn More </h4>
      <hr class="mt-3 mb-3">
      <p> Surf Swap is a platform where users can list their surf gear and other users can offer trades.</p> 
      <p>At this time, we are currently only working with Sufboards, but expect to increase this in the future 
        to include wetsuits, accessories and other surf related gear </p>
      <hr class="mt-2 mb-5">   
  </div>
</section>

src/surf_swap/app/views/pages/_popup_modal.html.erb
<div class="modal modal-alert position-static d-block bg-secondary py-5" tabindex="-1" role="dialog" id="modalChoice">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-body p-4 text-center">
        <h5 class="mb-0">Enable this setting?</h5>
        <p class="mb-0">You can always change your mind in your account settings.</p>
      </div>
      <div class="modal-footer flex-nowrap p-0">
        <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0 border-right"><strong>Yes, enable</strong></button>
        <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0" data-bs-dismiss="modal">No thanks</button>
      </div>
    </div>
  </div>
</div>

src/surf_swap/app/views/pages/_signup_modal.html.erb
<div class="modal modal-signin position-static d-block bg-secondary py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Sign up for free</h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body p-5 pt-0">
        <form class="">
          <div class="form-floating mb-3">
            <input type="email" class="form-control rounded-4" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control rounded-4" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
          </div>
          <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Sign up</button>
          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
          <hr class="my-4">
          <h2 class="fs-5 fw-bold mb-3">Or use a third-party</h2>
          <button class="w-100 py-2 mb-2 btn btn-outline-dark rounded-4" type="submit">
            <svg class="bi me-1" width="16" height="16"><use xlink:href="#twitter"></use></svg>
            Sign up with Twitter
          </button>
          <button class="w-100 py-2 mb-2 btn btn-outline-primary rounded-4" type="submit">
            <svg class="bi me-1" width="16" height="16"><use xlink:href="#facebook"></use></svg>
            Sign up with Facebook
          </button>
          <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-4" type="submit">
            <svg class="bi me-1" width="16" height="16"><use xlink:href="#github"></use></svg>
            Sign up with GitHub
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

src/surf_swap/app/views/pages/_user_controls.html.erb
<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">

  <li class="text-end">   
    <%= link_to "See your Gear", boards_path, class: "btn btn-outline-dark me-2 mb-3"  %>          
  </li>
  <li class="text-end">     
    <%= link_to "Add a Board", new_board_path, class: "btn btn-outline-dark me-2 mb-3"  %>          
  </li>
  <li  class="text-end">     
    <%= link_to "Create Listing", new_listing_path, class: "btn btn-outline-light me-2 mb-3"  %>          
  </li>
  <li  class="text-end">     
    <%= link_to "See My Listings", my_listings_path, class: "btn btn-outline-light me-2 mb-3"  %>          
  </li>
  <li  class="text-end">     
    <%= link_to "See  Meetups [#{@meetup_count}]", meetups_path, class: "btn btn-outline-dark me-2 mb-3"  %> 
  </li>
  <li></li>
  <li  class="text-end">     
    <%= link_to "Check Inbox #{"[0]"}", inbox_path, class: "btn btn-outline-dark me-2 mb-3"  %>          
  </li>

</ul>

src/surf_swap/app/views/pages/index.html.erb
<section 
class="d-flex h-100 text-center text-white bg-dark bg-image" 
style="background-image: url('https://images.pexels.com/photos/1753689/pexels-photo-1753689.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260');  
background-position: center;
background-repeat: no-repeat;
background-size: cover;
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
height:100vh;">

  <div class="cover-container d-flex w-100 h-100vh p-3 mx-auto flex-column" style="height:100vh">
  
    <header class="mb-auto">
        <h3 class="float-md-start mb-0 mb-3">SurfSwap</h3>
        <% if user_signed_in? %>
          <%= render 'user_controls'%>
        <% end %>    
    </header>

    <main class="px-3">
      <h1>swap - surf - save</h1>
      <br>
      <p class="lead">The place to find surfboards, wetsuits and ocean gear. Inspired by sustainable surfing and living free </p>
      <br>
      <p class="lead">
        <a href="#learn_more" class="btn btn-lg btn-secondary fw-bold border-white bg-black">Learn more</a>
      </p>
    </main>

    <footer class="mt-auto text-white-50">
      <p>Photo taken by <a href="https://www.pexels.com/@ging-ang-861233" class="text-white">Ging Ang</a></p>
    </footer>

  </div>
       
</section>
    
<br>
<%= render 'learn_more' %>
<br>
<%= render 'faqs' %>