src/surf_swap/config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/inbox', to: 'pages#inbox', as: 'inbox'

  #################### BOARDS ###############################

  get '/boards', to: 'boards#index', as: 'boards'
  post '/boards', to: 'boards#create'

  get '/boards/new', to: 'boards#new', as: 'new_board'

  get '/boards/:id', to: 'boards#show', as: 'board'
  delete '/boards/:id', to: 'boards#destroy'
  patch '/boards/:id', to: 'boards#update'
  
  get '/boards/:id/edit', to: 'boards#edit', as: 'edit_board'
  
  

#################### LISTINGS ###############################

  # TO LISTINGS
  get '/listings', to: 'listings#index', as: 'listings'
  post '/listings', to: 'listings#create'

  # NEW LISTING
  get '/listings/new', to: 'listings#new', as: 'new_listing'

  # SPECIFIC LISTING
  get '/listings/:id', to: 'listings#show', as: 'listing'
  patch '/listings/:id', to: 'listings#update'
  delete '/listings/:id', to: 'listings#destroy'

  # SPECIFIC LISTING + EDIT
  get '/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'

  ##################### USER LISTINGS ###########################

  get '/my-listings', to: 'listings#my_listings', as: 'my_listings'
  get '/user-listings/:id', to: 'listings#see_user_listings', as: 'see_user_listings'

  #################### offers ###############################

  get '/offers', to: 'offers#index', as: 'offers'
  post '/offers', to: 'offers#create'

  get '/listings/:id/offer/new', to: 'offers#new', as: 'new_offer'

  get '/offers/:id', to: 'offers#show', as: 'offer'
  patch '/offers/:id', to: 'offers#update'
 
  delete '/offers/:id', to: 'offers#destroy'

  get '/offers/:id/edit', to: 'offers#edit', as: 'edit_offer'


  #################### ACCEPT REJECT ###############################

  get '/reject-offer/:id', to: 'offers#reject_offer', as: 'reject_offer'
  get '/accept-offer/:id', to: 'meetups#create', as: 'accept_offer'
  get '/reset-offer/:id', to: 'offers#reset_offer', as: 'reset_offer'

  #################### MEETUPS ###############################

  get '/meetups', to: 'meetups#index', as: 'meetups'
  get '/meetups/new', to: 'meetups#new', as: "new_meetup"
  post '/meetups', to: 'meetups#create'
  
  get '/meetups/:id/edit', to: 'meetups#edit', as: 'edit_meetup'

  get '/meetups/:id', to: 'meetups#show', as: 'meetup'
  patch '/meetups/:id', to: 'meetups#update'
  delete '/meetups/:id', to: 'meetups#destroy'

  ##################### USER CANCELLATIONS ###########################

  get '/meetups/swap-completed/:id', to: 'meetups#swap_completed', as: 'swap_completed'
  get '/meetups/host-cancellation/:id', to: 'meetups#host_cancels', as: 'host_cancellation'
  get '/meetups/cancellation/:id', to: 'meetups#responder_cancels', as: 'responder_cancellation'
  
end

src/surf_swap/app/models/meetup.rb
class Meetup < ApplicationRecord
  belongs_to :listing
  belongs_to :offer
end

src/surf_swap/app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :authenticate_user!
  before_action :identify_offer, only: %i[create]
  before_action :identify_meetup_details, only: %i[host_cancels responder_cancels swap_completed destroy]
  before_action :check_if_authorised, except: :create

  include FormatTimedate # custom method in app/concerns

  def create
    authorize @this_offer
    # identify offer and listing for the meetup
    # before_action to identify offer
    @this_offer.update(status: 'accepted')

    @this_listing = Listing.find(@this_offer.listing_id)
    @this_listing.update(status: 'meetup_planned')

    # create the meetup with this information, however it is not yet completed
    Meetup.create!(listing_id: @this_listing.id, offer_id: @this_offer.id, completed: false)

    # go through the other offers for this listing and remove them
    @this_listing.offers.each do |offer|
      offer.destroy! unless offer == @this_offer
    end

    # remove any duplicate proposals (offers / listings) that the boards in this meetup are connected to
    remove_duplicate_board_proposals(@this_offer.boards)
    remove_duplicate_board_proposals(@this_listing.boards)

    # once all this is done, destroy the listing related to this meetup
    redirect_to meetups_path
  end

  def index
    relevant_listings = current_user.listings.map do |listing|
      listing.id
    end
    @hosted_meetups = Meetup.where(listing_id: relevant_listings)

    accepted_offers = current_user.offers.where(status: 'accepted').map do |offer|
      offer.id
    end
    @accepted_meetups = Meetup.where(offer_id: accepted_offers)
  end

  ##################### MEETUP OUTCOMES ###################################

  # this can only be actioned by host
  def host_cancels
    # before_action identify_meetup_details
    @meetup_listing.boards.each do |board|
      board.update!(status: "listed")
    end
    @meetup_offer.boards.each do |board|
      board.update!(status: "not listed")
    end
    # send notifications
    # destroy meetup and offer, but re-enable the listing status
    destroy
    @meetup_listing.update!(status: 'available')
    redirect_to root_path
  end

  # this can only be actioned by responder
  # the reason this function exists is so future different actions can be applied
  def responder_cancels
    # before_action identify_meetup_details
    @meetup_listing.boards.each do |board|
      board.update!(status: "listed")
    end
    @meetup_offer.boards.each do |board|
      board.update!(status: 'not listed')
    end
    # send notifications
    # destroy meetup and offer, but re-enable the listing status
    destroy
    @meetup_listing.update!(status: 'available')
    redirect_to root_path
  end

  def swap_completed
    identify_meetup_details
    @meetup[:completed] = true
    @swap_completed = @meetup.completed # stored as this value required after @meetup value deleted
    # Complete the surfboard trade
    meetup_board_transfer(@meetup_listing.boards.all, @meetup_offer.user.boards)
    meetup_board_transfer(@meetup_offer.boards.all, @meetup_listing.user.boards)
    # destroy the meetup and all meetup offer
    destroy
    # destroy the listing as well in this case, as swap has been completed, not cancelled
    @meetup_listing.destroy
    redirect_to root_path
  end

  def destroy
    # dependent: :destroy exists on the model Listing but was still required here
    @meetup.destroy!
    @meetup_offer.destroy!
    puts @swap_completed ? 'FIRST CONDITION' : 'SECOND CONDITION'
    @swap_completed ? @meetup_listing.destroy! : @meetup.listing.update![status: 'available']
  rescue StandardError => e
    puts '*' * 50
    puts 'Meetups Destroy Method not Completed'
    puts "Error: #{e.inspect}"
    puts '*' * 50
  end

  # ####################### PRIVATE METHODS ##################################
  private

  def identify_offer
    @this_offer = Offer.find(params[:id])
  end

  def identify_meetup_details
    @meetup = Meetup.find(params[:id])
    @meetup_listing = @meetup.listing
    @meetup_offer = @meetup.offer
  end

  def meetup_board_transfer(transfer_boards, receiver_collection)
    transfer_boards.each do |board|
      board.update!(status: 'Available')
      receiver_collection << board
    end
  end

  def remove_duplicate_board_proposals(board_group)
    # if the board has been accepted, then it shouldn't be in any other listings or offers
    board_group.each do |board|
      board.update!(status: 'Swap Agreed')
      remove_duplicate_offers(board)
      remove_duplicate_listings(board)
    end
  end

  def remove_duplicate_offers(board)
    board.offers.each do |offer|
      offer.destroy unless offer == @this_offer
      # notifications
    end
  end

  def remove_duplicate_listings(board)
    board.listings.each do |listing|
      # first remove all the offers from that listing
      next unless listing != @this_listing

      listing.offers.each do |offer|
        # notify others that the listing has been removed
        offer.destroy
      end
      listing.destroy!
    end
  end

  def check_if_authorised
    # using pundit, check the permissions
    authorize @meetup || Meetup
  end
end

src/surf_swap/app/helpers/meetups_helper.rb
module MeetupsHelper
end

src/surf_swap/app/views/meetups/_card_body.html.erb
<div class="card-body">

  <h3><%= listing.user == current_user ? "Your Items" : "Items from #{listing.user.first_name}" %></h3>
  <p><%= listing.user.phone %></p>
  <p class="card-text"> <%= listing.comment %> </p>
  <hr>

  <% listing.boards.each do |board| %>
    <p class="card-text"> Shaper/Designer: <%= board.designer%></p>
    <p class="card-text"> Description: <%= board.description%> </p>
    <hr>
  <% end %>

  <% offer = Offer.find(meetup.offer_id.to_i) %>
  <h3><%= offer.user == current_user ? "Your Items" : "Items from #{offer.user.first_name}" %></h3>
  <p><%= offer.user.phone %></p>
  <hr>
  <% offer.boards.each do |board| %>
    <p class="card-text">Shaper/Designer: <%= board.designer%></p>
    <p class="card-text">Description/Description: <%= board.description%> </p>
    <hr>
  <% end %>

src/surf_swap/app/views/meetups/_card_buttons.html.erb
<div class="d-flex justify-content-between align-items-center">
  <div class="btn-group">
  
    
    <% case meetup.listing.user %>
    <% when current_user %>
    <%= link_to "SWAP DONE", swap_completed_path(meetup), class: "btn btn-sm btn-outline-secondary", data: {confirm: "Great news! This will process the swap, and your inventory will be updated. Continue ?"}%>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to "CANCEL MEETUP", host_cancellation_path(meetup), class: "btn btn-sm btn-outline-secondary", data: {confirm: "Once clicked, this Meetup will be cancelled and the original listing will become active again. Continue ?"}%>
    
    <% else %>
      <%= link_to "CANCEL MEETUP", responder_cancellation_path(meetup), class: "btn btn-sm btn-outline-secondary", data: {confirm: "If you click this, the Meetup will be cancelled. Continue ?"}%>
    
    <% end %>

  </div>
</div>

src/surf_swap/app/views/meetups/_card_header.html.erb
<div class="p-2" style="background-color: lightyellow; color:darkslategray">

  Meet Date: <%= controller.formatted_date(listing.meetup_date) %> <%= controller.formatted_time(listing.meetup_time) %>
  <br>
  <%= listing.address.name %>
  <br>
  <%= listing.address.street_number %> <%= listing.address.street_name %>
  <br>
  <%= listing.address.suburb %>, <%= listing.address.postcode.state %>, <%= listing.address.postcode.number %>

</div>

src/surf_swap/app/views/meetups/_card_picture.html.erb
<%# cl_image_tag board.board_image.key, crop: :scale, width: 200, cloud_name: 'ddskwbftr' if board.board_image.attached?%>
<svg class="bd-placeholder-img card-img-top" 
width="100%" 
height="225" 
xmlns="http://www.w3.org/2000/svg" 
role="img" 
aria-label="Placeholder: Thumbnail" 
preserveAspectRatio="xMidYMid slice" 
focusable="false">
  <title>Placeholder</title>
  <rect width="100%" height="100%" fill="#55595c"></rect>
  <text x="20%" y="50%" fill="#eceeef" dy=".3em">Future Feature Slide. Stay Posted!</text>
</svg>

src/surf_swap/app/views/meetups/_header.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <br><br><br>
      <h1 class="fw-light" style="color:ghostwhite">Meetups</h1>
      <p class="lead text-muted">View all the Meetups you are hosting (top) and all the ones you are invited to (bottom)</p>

      <p>
        <a href="#hosted_meetups" class="btn btn-dark my-2">My Hosted Meetups</a>
        <a href="#approved_meetups" class="btn btn-light my-2">Invited to Meetups</a>
      </p>

    </div>
  </div>
</section>

<span style="font-style: italic; font-size:0.6em; color:azure">&nbsp;&nbsp;photo by Laker (pexels.com) </span>

src/surf_swap/app/views/meetups/_meetup_collection.html.erb
<div class="album py-5 bg-light" id="hosted_meetups">
  <div class="container">

    <h2><%= title %></h2>
    <% count = meetup_collection.count %>
    <% case count %>
    <% when 0 %>
      <p style="font-style: italic;">
        <%= none_msg %>
        <hr>
      </p>
    <% else %>
    <p style="font-style: italic;">You currently have <%= count %> <%= (count == 1 ) ? "Meetup" : "Meetups" %> planned</p>
    <hr>
    

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"> <!--full width div-->
      <div class="col">
        <div class="card shadow-lg" >

          <% meetup_collection.each do |meetup| %>
          
            <% listing = Listing.find(meetup.listing_id) %> 
            <%= render 'card_header', listing: listing %>
            <%= render 'card_picture' %>
            <%= render 'card_body', meetup: meetup, listing: listing %>
            <%= render 'card_buttons', meetup: meetup %>
        
          <% end %>

        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

src/surf_swap/app/views/meetups/index.html.erb
<main class="bg-image" 
style="background-image: url('https://images.pexels.com/photos/5792680/pexels-photo-5792680.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260');  
background-position: center;
background-repeat: no-repeat;
background-size: cover;
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
height:100vh;">

  <%= render 'header' %>

  <% none_msg = "No hosted Meetups are currently scheduled" %>
  <%= render 'meetup_collection', title: "Hosted Meetups", none_msg: none_msg, meetup_collection: @hosted_meetups %>

  <% none_msg = "None of your offers have been accepted for a Swap Meetup currently" %>
  <%= render 'meetup_collection', title: "Invited to Meetups", none_msg: none_msg, meetup_collection: @accepted_meetups %>

</main>