src/surf_swap/config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/inbox', to: 'pages#inbox', as: 'inbox'

  #################### BOARDS ###############################

  get '/boards', to: 'boards#index', as: 'boards'
  post '/boards', to: 'boards#create'

  get '/boards/new', to: 'boards#new', as: 'new_board'

  get '/boards/:id', to: 'boards#show', as: 'board'
  delete '/boards/:id', to: 'boards#destroy'
  patch '/boards/:id', to: 'boards#update'
  
  get '/boards/:id/edit', to: 'boards#edit', as: 'edit_board'
  
  

#################### LISTINGS ###############################

  # TO LISTINGS
  get '/listings', to: 'listings#index', as: 'listings'
  post '/listings', to: 'listings#create'

  # NEW LISTING
  get '/listings/new', to: 'listings#new', as: 'new_listing'

  # SPECIFIC LISTING
  get '/listings/:id', to: 'listings#show', as: 'listing'
  patch '/listings/:id', to: 'listings#update'
  delete '/listings/:id', to: 'listings#destroy'

  # SPECIFIC LISTING + EDIT
  get '/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'

  ##################### USER LISTINGS ###########################

  get '/my-listings', to: 'listings#my_listings', as: 'my_listings'
  get '/user-listings/:id', to: 'listings#see_user_listings', as: 'see_user_listings'

  #################### offers ###############################

  get '/offers', to: 'offers#index', as: 'offers'
  post '/offers', to: 'offers#create'

  get '/listings/:id/offer/new', to: 'offers#new', as: 'new_offer'

  get '/offers/:id', to: 'offers#show', as: 'offer'
  patch '/offers/:id', to: 'offers#update'
 
  delete '/offers/:id', to: 'offers#destroy'

  get '/offers/:id/edit', to: 'offers#edit', as: 'edit_offer'


  #################### ACCEPT REJECT ###############################

  get '/reject-offer/:id', to: 'offers#reject_offer', as: 'reject_offer'
  get '/accept-offer/:id', to: 'meetups#create', as: 'accept_offer'
  get '/reset-offer/:id', to: 'offers#reset_offer', as: 'reset_offer'

  #################### MEETUPS ###############################

  get '/meetups', to: 'meetups#index', as: 'meetups'
  get '/meetups/new', to: 'meetups#new', as: "new_meetup"
  post '/meetups', to: 'meetups#create'
  
  get '/meetups/:id/edit', to: 'meetups#edit', as: 'edit_meetup'

  get '/meetups/:id', to: 'meetups#show', as: 'meetup'
  patch '/meetups/:id', to: 'meetups#update'
  delete '/meetups/:id', to: 'meetups#destroy'

  ##################### USER CANCELLATIONS ###########################

  get '/meetups/swap-completed/:id', to: 'meetups#swap_completed', as: 'swap_completed'
  get '/meetups/host-cancellation/:id', to: 'meetups#host_cancels', as: 'host_cancellation'
  get '/meetups/cancellation/:id', to: 'meetups#responder_cancels', as: 'responder_cancellation'
  
end

src/surf_swap/app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :address

  has_one :meetup, dependent: :destroy

  has_many :offers, dependent: :destroy

  has_many :board_listings, dependent: :destroy
  has_many :boards, through: :board_listings


  ################### VALIDATIONS ###########################

  validates :header, presence: {message: "Please provide a title for this listing"}
  
  validates :address, presence: { message: "Please provide an address for a proposed meetup"}
  validates :meetup_date, presence: { message: "Please provide a date for a proposed meetup"}
  validates :meetup_time, presence: { message: "Please provide a time for a proposed meetup"}

  validates :boards, presence: { message: "You must select a board to create a listing"}
  validates :comment, presence: {message: "Please provide a short message about this listing"}

  validate :check_if_past_date

def check_if_past_date
  unless meetup_date.nil?
    if meetup_date < Date.today
      errors.add(:meetup_date, "Cannot set date before today") 
    end
  end
end


end

src/surf_swap/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :identify_listing, only: %i[show edit update destroy]
  before_action :identify_boards, only: %i[create show edit update destroy]
  before_action :preload_addresses, only: %i[new create edit update]
  before_action :check_if_authorised, except: %i[index my_listings see_user_listings]
  before_action :check_availability_prior_listing, only: %i[new]

  include FormatTimedate

  def index
    # before_action identify_boards
    @listings = Listing.where(status: 'available')

    @no_listings_msg = "Sorry, no currently available listings.
    Please check back later or make one yourself !"

    @title = 'Surfboard Listings'
    @descriptive_line1 = 'Find a board below that you want to check out!'
    @descriptive_line2 = '(Some boards are part of a multi-item swap only)'
  end

  def my_listings
    @no_listings_msg = "You don't have any current listings. Do you want to make one ?"
    @listings = Listing.where(user: current_user)
    @title = 'Your Surfboard Listings'
    @descriptive_line1 = 'Select view to check any offers'
    @descriptive_line2 = '(all listings included, even those with Meetups)'

    render 'index'
  end

  def see_user_listings
    listing = Listing.find(params[:id])
    user = User.find(listing.user.id)

    @listings = Listing.where(user: user, status: 'available')
    @title = "Surfboard Listings by #{user.first_name}"
    @descriptive_line1 = 'Find a board below that you want to check out!'
    @descriptive_line2 = '(Some boards are part of a multi-item swap only)'

    render 'index'
  end

  def new
    # before_action identify_boards
    # before_action preload_addresses
    @listing = Listing.new
    @boards = current_user.boards.where.not(status: 'Swap Agreed')
  end

  def create
    # before_action identify_boards
    # before_action preload_addresses

    params_hash = listing_params
    params_hash[:user] = current_user
    # separated lines as adding :user value to listing_params does not work
    @listing = Listing.new(params_hash)
    @addresses = Address.all

    if @listing.valid?
      @listing.save

      # status is set to available to stop Listings with Meetups appearing
      @listing.update!(status: 'available')

      # updating the status of boards to listed, to allow more precise queries elsewhere
      @listing.boards.each do |board|
        board.update!(status: 'currently_listed')
      end

      redirect_to listings_path

    else
      flash.now[:errors] = @listing.errors.messages.values.flatten
      render :new

    end
  end

  def update
    # before_action identify_listing
    # before_action preload_addresses

    @listing.update!(listing_params)

    @listing.offers.each do |offer|
      offer.destroy!
      # remove all offers, send notification
    end
    redirect_to @listing

  rescue StandardError
    flash.now[:errors] = @listing.errors.messages.values.flatten
    render :edit
  end

  def edit
    # before_action identify_listing
    # before_action preload_addresses
    @boards = current_user.boards.where.not(status: 'Swap Agreed')
  end

  def destroy
    # before_action identify_listing
    # Meetups and Offers are have a dependency destroy constraint
    @listing.destroy!
    # send a message to other users
    redirect_to listings_path
  end

  def show
    # before_action identify_listing
    @host = User.find(@listing.user_id)

    @item_count = @listing.boards.count
    @offer_count = @listing.offers.count

    # using the FormatTimedate module
    @date = formatted_date(@listing.meetup_date)
    @time = formatted_time(@listing.meetup_time)

    @available_board_count = count_available_boards
  end

  ##################### PRIVATE #####################################
  private

  def listing_params
    params.require(:listing).permit(:user_id, :header, :status, :meetup_date, :meetup_time, :address_id, :comment,
                                    :created_at, board_ids: [])
    # params.require(:board).permit(:cover_image, :title, :publisher, :data_published, :author_id, genre_ids: [])
  end

  def identify_listing
    @listing = Listing.find(params[:id])
  end

  def identify_boards
    @boards = Board.where(user: current_user)
  end

  def preload_addresses
    @addresses = Address.all
  end

  def check_if_authorised
    # using pundit, check the permissions
    authorize @listing || Listing
  end

  def check_availability_prior_listing
    unless count_available_boards.positive?
      flash[:notice] = 'Sorry, you have no available boards to create a new listing'

      redirect_to(request.referrer || root_path)
      # return to previous URL or to home page
    end
  end

  def count_available_boards
    available_boards = current_user.boards.select(:status).where.not(status: 'Swap Agreed')
    if available_boards.nil?
      0
    else 
      available_boards.count
    end
  end
  

end

src/surf_swap/app/helpers/listings_helper.rb
module ListingsHelper
end

src/surf_swap/app/views/listings/_index_header.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light"><%=@title%></h1>
      <br>
      <p class="lead text-muted"><%=@descriptive_line1%><br>
        <span style="font-style: italic"><%=@descriptive_line2%></span>
      </p>
      <br>
      <br>
      <p>
        
        <%= link_to "See all Listings", listings_path, class: "btn btn-dark my-2" %>
        <% if user_signed_in? %>
        <%= link_to "See my Listings", my_listings_path, class: "btn btn-dark my-2" %>
        <% end %>
        <!-- <h4>Consider a search option here</h4> -->
      </p>
    </div>
  </div>
</section>
<span style="font-style: italic; font-size:0.6em; color:azure">&nbsp;&nbsp;photo by Bradley Hook (pexels.com) </span>

src/surf_swap/app/views/listings/_show_top_buttons.html.erb
<% if @host != current_user %>

 
  <% case @available_board_count %>
  <% when 0 %>

    <p style="color:darkslateblue"> You do not have any boards available to offer a swap. Please add one from the Home Page menu</p>

  <% else %> 
    <h3><%= link_to "Offer a SWAP", new_offer_path, class: "btn btn-outline-dark me-2" %></h3>
  <% end %>

  <br>
  <p>
    <%= link_to "Click to see all listings from #{@host.first_name}", see_user_listings_path(@listing) %> 
  </p>

<% elsif @host == current_user %>

  <% case @listing.status %>
  <% when "meetup_planned" %>
    <p>This offer has now been accepted and a formal Meetup has been arranged.
      If you no longer want to accept this offer, please cancel the meetup</p>
  <% else %>
    <%= link_to "Edit My Listing", edit_listing_path(@listing), class: "btn btn-outline-dark me-2", data: {confirm: "Editing a listing will delete current offers under consideration and a message will be sent to those users. Please confirm"} %>
    <%= link_to "Delete My Listing", listing_path(@listing), class: "btn btn-outline-dark me-2", method: :delete, data: {confirm: "This will delete listing and all offers. Please confirm"}%>
  <% end %>

<% end %>

<br><br>

src/surf_swap/app/views/listings/index.html.erb
<main
  class="bg-image" 
  style="background-image: url('https://images.pexels.com/photos/111085/pexels-photo-111085.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260');  
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  height:100vh;">

  <%= render 'index_header' %>


  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        <% case @listings.count %>
        <% when 0 %>

          <div class="text-start p-3" style="font-style: italic; border: solid 1px red"> 
            <p><%= @no_listings_msg %></p>
            <%= link_to "Create New Listing", new_listing_path, class: "btn btn-outline-dark me-2"  %>          
          </div>

        <% else %>

          <% @listings.each do |listing| %>

            <% case listing.boards.count %>
            <% when 1 %>
              <% swap_type = 'This is a "Single-Item" Swap' %>
            <% else %> 
              <% swap_type = 'Part of a "Multi-Item" Swap' %>
            <% end %>

            <% listing.boards.each do |board| %>

              <div class="col">
                <% case board.user %>
                <% when current_user %>
                  <div class="card shadow-sm" style="border: solid 1px yellow">
                  <% @descriptor = "#{swap_type} that you listed" %>
                <% else %>
                  <div class="card shadow-sm">
                    <% @descriptor = "#{swap_type} from #{listing.user.first_name}" %>
                <% end %>

                
                  <div class="p-2" style="background-color: lightblue; color:darkslategray">
                    Created: <%= controller.formatted_date(listing.created_at) %>
                    <p>Location: <%= listing.address.suburb %>, <%= listing.address.postcode.state %> <%= listing.address.postcode.number %> </p>
                    <p style="font-style: italic;"><%=@descriptor %> </p>
                  </div>
                  
                  <%= cl_image_tag board.board_image.key, crop: :scale, width: 200, cloud_name: 'ddskwbftr' if board.board_image.attached?%>
              
                  <div class="card-body">
                    <p class="card-text">Shaper: <%= board.designer%> </p>
                    <p class="card-text">Description: <%= board.description%> </p>
                    <hr class="mt-2 mb-2">
                    
                    <p class="card-text"> <%= listing.comment %> </p>
                    <div class="d-flex justify-content-between align-items-center">

                      <div class="btn-group">
                        <%= link_to "View Listing", listing_path(listing), class: "btn btn-sm btn-outline-secondary" %>
                      </div>


                      <% count = listing.offers.count %>
                      <% offer_term = "current_offers" %>
                      <% case listing.offers.count %>
                      <% when 1 %>
                        <% offer_term = "current offer" %>
                
                      <% else %>
                        <% offer_term = "current offers" %>
                     
                      <% end %>
                      <small class="text-muted"><%= count %> <%= offer_term %></small>
                      
                    </div>
                  </div>
                </div>
              </div>

            <% end %>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>

</main>

src/surf_swap/app/views/listings/show.html.erb
<!-- Page Content -->

<!-- ################ HEADER ############################# -->

<div class="container">

  <h1 class="fw-light text-center text-lg-start mt-4 mb-0">Surfing Gear Swap from  <%= @host.first_name %></h1>
  <h4 class="fw-light text-center text-lg-start mt-4 mb-0"><%= @listing.header %></h4>

  <hr class="mt-2 mb-3">

 
  <%= render 'show_top_buttons' %>


  <!-- ###################### LISTING DETAILS ######################### -->



  <h4> Proposed Meetup Details </h4>
 
  <p style="padding-left: 10px"><%= @listing.address.name %></p>
  <span style="padding-left: 10px"><%= @listing.address.street_number %> <%= @listing.address.street_name %></span>
  <br>
  <span style="padding-left: 10px"><%= @listing.address.street_name %></span>

  <p style="padding-left: 10px"><%= @listing.address.suburb %> <%= @listing.address.postcode.state %> <%= @listing.address.postcode.number %></p>
  <p style="padding-left: 10px; background-color:lightyellow"><%= @time %> on the <%= @date %></p>

  <p style="padding-left: 10px; font-style:italic"><%= @listing.comment %></p>

  <div class="row text-center text-lg-start" style="border:3px solid green">




  <%= render 'show_panel', proposal: @listing %>
    
   
  </div>

</div>


<!-- ################### ALL OFFERS ################### -->


<% case @offer_count %>
<% when 0 %>
  <% comment = "No current offers" %>
<% end %>

<div class="container">

  <h2 class="fw-light text-center text-lg-start mt-4 mb-0">All Offers</h2>
 
  <% case @offer_count %>
  <% when 0 %>
    <p> No current offers <p>
  <% end %>


  <hr class="mt-2 mb-5">

<!-- ##################### LISTING ITERATIONS ########################### -->

  <% @listing.offers.each do |offer| %>

    <p>Offer created: <%= controller.formatted_date(offer.created_at) %></p>
    <span> From: <%= offer.user.first_name %></span>
    <p> <%=offer.comment %></p>
    
    <% if @host == current_user %>

      <% case offer.status %>
      <% when "accepted" %>
        <p style="font-style:italic; color: darkslategray"> This offer has now been accepted and a formal Meetup has been arranged.
          If you no longer want to accept this offer, please cancel the meetup </p>

      <% when "rejected" %>
        <%= link_to "Undo Rejection", reset_offer_path(offer.id), class: "btn btn-outline-dark me-2" %>
        <%= link_to "Delete Offer", offer_path(offer.id), method: :delete, class: "btn btn-outline-dark me-2" %>

      <% else %>
        <%= link_to "Accept Offer", accept_offer_path(offer.id), class: "btn btn-outline-dark me-2", data: {confirm: "Accepting this offer will automatically create a Meetup with #{offer.user.first_name}. Please confirm"} %>
        <%= link_to "Reject Offer", reject_offer_path(offer.id), class: "btn btn-outline-dark me-2", data: {confirm: "This will reject the offer and notify #{offer.user.first_name}. Please confirm"}%>
      
      <% end %>

    <% elsif offer.user == current_user %>

      <div>
        
        <%= link_to "Edit My Offer", edit_offer_path(offer), class: "btn btn-warning me-2" %>
        &nbsp;&nbsp;
        <%= link_to "Remove My Offer", offer_path(offer), method: :delete, class: "btn btn btn-warning me-2" %>
      </div>

    <% end %>


  <!-- ##################### OFFER ITEMS ########################### -->
    <!-- ##################### BORDER ########################### -->
    <br><br>

    <% case offer.status %>
    <% when "accepted" %>

      <div class="row text-center text-lg-start bg-image mb-5" style="border:3px solid green;
      background-image: url('https://toppng.com/uploads/preview/accepted-1-cajo-records-canton-jones-dominionaire-remixed-cd-11563075835t8gowlqrde.png');  
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      height:100%;">


    <% when "reconsidered" %>
      <div class="row text-center text-lg-start" style="border:3px solid gray">

    <% when "rejected" %>

      <div class="row text-center text-lg-start bg-image mb-5" style="border:3px solid red; background-color: grey;
      background-image: url('https://toppng.com/uploads/preview/red-rejected-stamp-11523441388utb5fruxox.png');  
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      height:100%;">
      
    
    <% else %>
      <div class="row text-center text-lg-start mb-5" style="border:3px solid gray">
    <% end %>
    
 <!-- ##################### OFFER ITEMS CONT ########################### -->
    <!-- ##################### BOARD ITERATIONS ########################### -->


        <%= render 'show_panel', proposal: offer %>

        
      </div>

<!-- ##################### CLOSE LISTING AND CONTAINER ########################### -->
    
  <% end %>     
  <br>
  <br> 
</div>

src/surf_swap/app/views/listings/showED.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Surfing Gear from  <%= @host.first_name %> </h1>
        <p class="lead text-muted">Checkout details of swap and make an offer</p>
        <p>
          <%= link_to "See all listings from #{@host.first_name}", new_board_path, class: "btn btn-primary my-2"  %> 
          <a href="#" class="btn btn-secondary my-2">See Something Else</a>
          <h4>Consider a search option</h4>
        </p>
      </div>
    </div>
  </section>

  <h1> <%= @listing.header %></h1>
  <h2> SWAP LOCATION </h2>
  <p><%= @listing.address.name %></p>
  <p><%= @listing.address.street_name %></p>
  <p><%= @listing.address.suburb %></p>
  <h1> <%= @listing.meetup_time %></h1>

  <% case @item_count %>
  <% when 1 %>
  <h2> Single Item <%= @host.first_name %> wants to swap </h2>
  <% else %>
  <h2> Swap-pack <%= @host.first_name %> wants to trade </h2>
  <% end %> 


  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">


        <%# case @boards.count %>
        <%# when  %>
          <!-- <h2>No boards currently. Please add one to allow trading</h2> -->
        <%# end %>

        <% @listing.boards.each do |board| %>

        
        <div class="col">
          <div class="card shadow-sm" >
            <div style="background-color: lightblue; color:darkslategray">
              <p class="card-text">
                <%= board.designer %> (Nickname?)
              </p>
          
            </div>
            
            <%= cl_image_tag board.board_image.key, crop: :scale, width: 200, cloud_name: 'ddskwbftr' if board.board_image.attached?%>
            <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->


            <div class="card-body">

             
              <p class="card-text">Length: <%= board.length %></p>
              <p class="card-text">Width: <%= board.width %></p>
              <p class="card-text">Volume: <%= board.volume %></p>
              <p class="card-text">Fin Type: <%= board.fins %></p>
              <p class="card-text">Tail Type: <%= board.tail %></p>
              <p class="card-text">Attachments: <%= board.attachments %></p>
              <p class="card-text">Description: <%= board.description %></p>


              <div class="d-flex justify-content-between align-items-center">

         
          


                <div class="btn-group">

                  <%= link_to "Edit", edit_board_path(board), class: "btn btn-outline-dark me-2" %>
                  &nbsp;&nbsp;&nbsp;&nbsp;
                  <%= link_to "Delete", board_path(board), method: :delete, class: "btn btn-outline-dark me-2", data: {confirm: "This will delete board. Are you sure?"} %>
     
                </div>
                <small class="text-muted">0 views</small>
              </div>
            </div>
          </div>
        </div>

      
       <% end %>

      </div>
    </div>
  </div>

</main>

src/surf_swap/app/views/listings/showOL.html.erb
<h1> Surfing Gear from  <%= @host.first_name %> </h1>


<h1> <%= @listing.header %></h1>

<div>

  <h2> SWAP LOCATION </h2>
  <p><%= @listing.address.name %></p>
  <p><%= @listing.address.street_name %></p>
  <p><%= @listing.address.suburb %></p>
  <h1> <%= @listing.meetup_time %></h1>

  <% case @item_count %>
  <% when 1 %>
  <h2> Single Item <%= @host.first_name %> wants to swap </h2>
  <% else %>
  <h2> Swap-pack <%= @host.first_name %> wants to trade </h2>
  <% end %> 


  <% @listing.boards.each do |board| %>


  <%= cl_image_tag board.board_image.key, crop: :scale, width: 400, cloud_name: 'ddskwbftr' if board.board_image.attached?%>
  <%# NEW IMAGE COMMAND   ASSC.   .KEY METHOD  CROP: :SCALE to WIDTH      CLOUD NAME SPECIFIC %>

    <div style="margin: 10px; padding: 10px; background-color: lightgreen; width: 300px">
      <p>Designer: <%= board.designer%></p>
      <p>Length: <%= board.length%></p>
      <p>Width: <%= board.width %></p>
      <p>Volume: <%= board.volume %></p>
      <p>Fin Type: <%= board.fins %></p>
      <p>Tail Type: <%= board.tail %></p>
      <p>Attachments <%= board.attachments %></p>
      <p>Description: <%= board.description %></p>
    </div>

  <% end %>

  <% if @host != current_user %>
    <h3><%= link_to "Offer a SWAP", new_offer_path %></h3>
    <br>
    <p> Click to <%= link_to "see all listings from #{@host.first_name}", root_path %> </p>

    <% elsif @host == current_user %>
    <p><%= link_to "Edit Listing", edit_listing_path(@listing), data: {confirm: "Editing a listing will delete current offers under consideration and a message will be sent to those users. Please confirm"} %></p>
    <p><%= link_to "Delete Listing", listing_path(@listing), method: :delete, data: {confirm: "This will delete listing and all offers. Please confirm"}%> </p>
  <% end %>


<h1 style="color:darkblue"> ##################################################### </h1>


<%# ############################ OFFERS ####################################### %>

<% case @offer_count %>
<% when 0 %>
  <p> No current offers </p>
<% end %>

<% begin %>

  <% @listing.offers.each do |offer| %>

  CONSIDER making an html class to determine the colors or embedded @color etc.

    <% case offer.status %>
    <% when "accepted" %>
      <section style="background-color: green; width: 300px;" class="CHOOSESOMETHING">
    <% when "rejected" %>
      <section style="background-color: grey; width: 300px;">
    <% else %>
      <section style="background-color: pink; width: 300px;">
    <% end %>

    
      <% date_time = offer.created_at.to_s.chars %>
      <p> <%= date_time[0..9].join %>  </p>
    
      <h3> OFFER <%=offer.id %> </h2>

        <p > STATUS : [ <%= offer.status %> ] </p>

        <p> <% offer.boards.each do |offerer_board| %> </p>
        <div style="background-color: lightgray;">

          <%= cl_image_tag offerer_board.board_image.key, crop: :scale, width: 400, cloud_name: 'ddskwbftr' if offerer_board.board_image.attached?%>
          <%# NEW IMAGE COMMAND   ASSC.   .KEY METHOD  CROP: :SCALE to WIDTH      CLOUD NAME SPECIFIC %>

          <p>Designer: <%= offerer_board.designer %></p>
          <p>Length: <%= offerer_board.length %></p>
          <p>Width: <%= offerer_board.width %></p>
          <p>Volume: <%= offerer_board.volume %></p>
          <p>Fin Type: <%= offerer_board.fins %></p>
          <p>Tail Type: <%= offerer_board.tail %></p>
          <p>Attachments: <%= offerer_board.attachments %></p>
          <p>Comments: <%= offerer_board.description %></p>

          <%# render 'board_attributes', button_name: "Launch New Listing"%>
          
        </div>

        <% end %>
        
      <h3> QUESTIONS / COMMENTS </h2>
      <p> <%= offer.comment %> </p>
      
      <p>&nbsp;&nbsp; <%= offer.user.first_name %> </p>



  <%# ########################  OFFER OPTIONS ####################################### %>
  <%# https://stackoverflow.com/questions/6247491/rails-3-display-link-as-button %>

      
    <% if @listing.user == current_user %>

      <% case offer.status %>
      <% when "accepted" %>
      <p> this offer has been accepted and a Meetup has been formed. If you no longer want to accept this offer, please cancel the meetup and this entry will automatically be under consideration</p>

      <% when "rejected" %>
        <p>click here to undo the rejection (offer will be back under consideration and user notified)</p>
        <p style="background-color: yellow; width: 150px; height: 30px"> <%= link_to "Undo Rejection", reset_offer_path(offer.id) %></p>

      <% else %>
        <p style="background-color: yellow; width: 150px; height: 30px"> <%= link_to "ACCEPT OFFER", accept_offer_path(offer.id) %></p>
        <p style="background-color: yellow; width: 150px; height: 30px"> <%= link_to "REJECT OFFER", reject_offer_path(offer.id) %></p>
        
      <% end %>

    <% elsif offer.user == current_user %>
      <p style="background-color: yellow; width: 150px; height: 30px"> <%= link_to "EDIT OFFER", edit_offer_path(offer.id) %></p>
      <p style="background-color: yellow; width: 150px; height: 30px"> <%= link_to "REMOVE OFFER", reject_offer_path(offer.id) %></p>

    <% end %>
        
    <h1>&nbsp;&nbsp; <%= offer.user.first_name %> </h1>
      

  <% end %>

      <p>SEND MESSAGE TO <%=offer.user.first_name %></p>
      
  </section>




<% rescue %>

<% end %>